apiVersion: v1
kind: Pod
metadata:
  name: devboard-frontend
  namespace: devboard
spec:
  containers:
  - name: devboard-frontend
    image: adnansyed1928/deboard-fe
    ports:
    - containerPort: 4173

