apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devboard
spec:
  selector:
    app: devboard-postgres    #deploy name labels
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432        #port postgres
