#Goal: to install multiple version of Go and do linting for multiple version

name: Go linter
on:
  workflow_dispatch:

jobs:
  frontend:
      runs-on: ubuntu-latest
      strategy:
      fail-fast: false                        #if any version fail it will run #false
      matrix:
        node-version: [22, 24, 26] 

      steps:
        - name: checkout code
          uses: actions/checkout@v7

        - name: setup Node.job
          uses: actions/setup-node@v6
          with:
            node-version: ${{matrix.node-version}}         #call the matrix
            cache: npm
            cache-dependency-path: 'frontend/package-lock.json'

        - name: install npm package
          run: npm install --force
          working-directory: frontend

        - name: run linter
          run: npm run lint
          working-directory: frontend
        
        - name: run test
          run: npm run test
          working-directory: frontend


  code-formate backend:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false                        #if any version fail it will run #false
      matrix:
        go-version: [1.22, 1.23, 1.24]         #this part will run as a for loop
    
    steps:
      - name: checkout code
        uses: actions/checkout@v7

      - name: setup Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}                    #in this we have to assing the loop
          cache: true
          cache-dependency-path: 'backend/go.sum'

      - name: run Go formater
        run: go fmt
        working-directory: backend

      - name: Run Go vet
        run: go vet
        working-directory: backend
      
      - name: run test
        run: go test
        working-directory: backend

      